elifesciences/journal-formula

salt/journal/init.sls

Integrates https://github.com/elifesciences/journal-formula/pull/1

Composer improvements

---

salt/journal/init.sls

Check Nginx stays up until a timeout has elapsed

---

salt/journal/config/srv-journal-app-config-parameters.yml

This should inject Redis configuration into parameters.yml, when the time comes

Inject ElastiCache Redis configuration

---

salt/example.top
salt/journal/api-dummy.sls
salt/journal/config/etc-nginx-sites-enabled-journal-local-demo.conf
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/journal/critical-css.sls
salt/journal/init.sls

Deploys and enables the virtual host, but the parameters need to be tweaked to disable Redis and similar dependencies.

Moving journal-local-demo into its own folder

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/pillar/journal.sls

For https://github.com/elifesciences/journal/pull/751

Add WebP feature flag config

---

salt/journal/config/srv-journal-local-demo-app-config-parameters.yml

Add WebP feature flag config for demo

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

Depends on https://github.com/elifesciences/builder-private/pull/106

ELPP-3335 Add redis_cache and redis_sessions parameters

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

Was removed in https://github.com/elifesciences/journal/pull/809.

Remove WebP feature flag

---

salt/journal/config/srv-journal-app-config-parameters.yml

Hopefully addresses https://github.com/elifesciences/journal/pull/806#discussion_r157982923.

Use yaml filter in Jinja

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

For https://github.com/elifesciences/journal/pull/853.

Add feature_can_always_use_hypothesis parameter

---

salt/journal/critical-css.sls

Builds on https://github.com/elifesciences/journal/pull/803

Add smoke test for critical css

---

Jenkinsfile

Try to do as much as possible in parallel, via building different instances

Experiment with parallel build

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

Now that https://github.com/elifesciences/journal/pull/852 is merged.

ELPP-3306 Remove Disqus parameters

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

For https://github.com/elifesciences/journal/pull/870.

Add subject_rewrites parameter

---

salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf

Should have been done before https://github.com/elifesciences/builder-private/pull/142 / https://github.com/elifesciences/builder-private/pull/144.

Redirect old subjects

---

salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf

See: https://github.com/elifesciences/journal-cms/pull/303

Add Chromosomes and Gene Expression redirects

---

salt/journal/config/etc-nginx-sites-available-journal.conf
salt/journal/config/etc-nginx-sites-enabled-journal-local-demo.conf
salt/journal/config/srv-journal-behat.yml

Requires https://github.com/elifesciences/journal/pull/954

ELPP-3323 Use single front controller

---

salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf

Depends on https://github.com/elifesciences/journal/pull/960.

Update redirects for privacy notice

---

salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf

See: https://github.com/elifesciences/journal-cms/pull/310

ELPP-3593 Add Genomics and Evolutionary Biology redirects

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

Required by https://github.com/elifesciences/journal/pull/962. Requires https://github.com/elifesciences/builder-private/pull/174.

ELPP-3654 Add cookie_consent parameter

---

salt/journal/config/etc-nginx-sites-available-journal.conf

From failed integration with ELB on journal--end2end.

ELPP-3393 Only pass X-Forwarded-Host if not empty

---

salt/journal/local-demo.sls

Required file introduced in https://github.com/elifesciences/journal/pull/964.
Should fix https://alfred.elifesciences.org/job/test-journal/1461/.

Copy elife-loader.js to local demo

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

Required by https://github.com/elifesciences/journal/pull/1021.

Make Cache-Control directives configurable

---

salt/journal/config/etc-nginx-sites-available-journal.conf
salt/journal/config/etc-nginx-sites-enabled-journal-local-demo.conf

Remove obsolete front controller blocks

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

Required by https://github.com/elifesciences/journal/pull/1027.

Set feature_digest_channel

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

Required by https://github.com/elifesciences/journal/pull/1073.

Add xPub configuration

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

https://github.com/elifesciences/journal/pull/1086 has just been merged.

Remove feature_digest_channel

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

To deploy https://github.com/elifesciences/journal/pull/1115
Depends on https://github.com/elifesciences/builder-configuration/pull/30

Configure reproducible document ids and links

---

salt/journal/config/srv-journal-app-config-parameters.yml
salt/journal/config/srv-journal-local-demo-app-config-parameters.yml
salt/pillar/journal.sls

For https://github.com/elifesciences/issues/issues/4769
Depends on https://github.com/elifesciences/builder-configuration/pull/36

Add calls_to_action parameter

---

salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf

Improves: https://github.com/elifesciences/issues/issues/4796

Add redirects to michael eisen’s press package

---

salt/journal/config/etc-nginx-sites-available-journal.conf
salt/journal/config/srv-journal-nginx-assets.conf
salt/journal/init.sls

Part of https://github.com/elifesciences/issues/issues/3676
- Pull only main image
- Move `add_header` to nginx container

Adjustment of container-based formula

---

salt/journal/init.sls

Part of elifesciences/issues#3676

Removes sites as soon as possible

---

salt/journal/config/srv-journal-docker-compose.yml

Part of https://github.com/elifesciences/journal-formula/pull/90

Restart all containers on boot

---

salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf

Improves: https://github.com/elifesciences/issues/issues/5008

Add redirects to platform Libero publisher press package

---

salt/journal/init.sls

- Remove `setgid` bit complexity
- Remove obsolete service stopping state
- Remove git repository absence state
- Avoid removing file that does not exists anymore

Simplify `var/` folder and similar

---

salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf

Improves: https://github.com/elifesciences/issues/issues/5061

Add redirect for executive director job page

---

salt/journal/config/srv-journal-parameters.yml
salt/pillar/journal.sls

For https://github.com/elifesciences/journal/pull/1210
Depends on https://github.com/elifesciences/builder-configuration/pull/1
/cc @discodavey

Add dismissible_info_bars configuration

---

salt/journal/config/etc-nginx-traits.d-robots.conf
salt/pillar/journal.sls

they did 16.2k requests across 4 ips to /search in less than 12 hours

robots.txt, adds /search to disallowed paths for bingbot

---

salt/journal/config/srv-journal-parameters.yml
salt/pillar/journal.sls

For https://github.com/elifesciences/issues/issues/5344

Rename configuration to example_rds_articles

---

salt/journal/config/srv-journal-parameters.yml
salt/pillar/journal.sls

Depends on https://github.com/elifesciences/journal/pull/1223

Remove deprecated rds_articles

---

salt/journal/config/srv-journal-parameters.yml
salt/pillar/journal.sls

https://github.com/elifesciences/issues/issues/5347
For https://github.com/elifesciences/journal/pull/1220.

Add RDS articles feature

---

salt/journal/config/srv-journal-parameters.yml
salt/pillar/journal.sls
salt/pillar/rds-articles.yaml

Follow-up https://github.com/elifesciences/builder-configuration/pull/119
On `journal.rds_articles.*.date`

Reproduce YAML quoting issue in Vagrant

---

salt/journal/config/etc-nginx-sites-available-journal.conf
salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf

For https://github.com/elifesciences/issues/issues/5542
```
[elife@journal--vagrant:~]$ curl -v localhost/highlights
> GET /highlights HTTP/1.1
> Host: localhost
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< ...
< Location: https://crm.elifesciences.org/crm/highlights
< Cache-Control: public, max-age=604800
<
```

Fix external URLs redirects

---

salt/journal/config/srv-journal-parameters.yml

related to libero/reviewer#1041
adds submit_url_redirects parameter to standard keys

added submit_url_redirects

---

salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf

This reverts commit b37ebd376df1b6de1398c0ffba6b761e767ecda0.

Revert "Redirect to new ERA labs post for RDS labs post (#123)"

---

salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf

This reverts commit fe895d43623e1b0410b3e3fd5cfe518b60819bb3.
This cannot be merged and deployed until the following is deployed: https://github.com/stencila/thema/pull/239

Revert "Redirects to new labs post for executable versions (#125)"

---

salt/pillar/journal.sls

This reverts commit e0af509d75f2deb1cf5af63cc7cb4e0f62bb5e87.

Revert "replaces mentions of xpub (#133)"

---

salt/journal/config/srv-journal-parameters.yml
salt/pillar/journal.sls

This reverts commit 2e0a682fedcbe5bd2f051a18c6d81b25c23c82f2.

replaces mentions of xpub

---

salt/journal/config/etc-nginx-sites-available-journal.conf

fixes bug with nginx using ssl when no certs configured.

---

salt/journal/config/etc-nginx-sites-available-journal.conf

https://github.com/elifesciences/enhanced-preprints-issues/issues/685

nginx, adds header for pubpub proxy so they can id our traffic

---

salt/journal/config/etc-nginx-sites-available-journal.conf
salt/pillar/journal.sls

@lsh-0 please review this PR and provide me with some feedback

/media-policy redirect to pubpub

---

salt/journal/config/etc-nginx-sites-available-journal.conf
salt/pillar/journal.sls

Hey @scottaubrey please review this, I got a bit confused for a while but I think I got it right now according to HubSpot documentation https://developers.hubspot.com/beta-docs/guides/cms/content/performance/reverse-proxy-support#configure-the-proxy

set journal proxy to hubspot elifesciences/issues#9017

---

salt/journal/config/etc-caddy-sites.d-journal

Pass HTTPS on header to nginx/journal elifesciences/issues#9202
