elifesciences/journal-formula

salt/journal/init.sls
This was breaking on new instances. The direct apt-get command works more reliably, for some reason (problem must be in the `pkg.installed` Salt state).
=> Installing the PHP redis extension safely on new VMs

salt/journal/config/etc-nginx-sites-enabled-journal.conf
Introduces default_server which we tried to avoid, but direct traffic should be stopped by firewalls and untrusted bad hosts should be stopped by Journal's PHP code
=> Redirect developers.elifesciences.org

salt/journal/config/srv-journal-app-config-parameters.yml, salt/pillar/journal.sls
To avoid configuring explicitly every environment, this would be the non-CDN version even where available; URL still will work.
=> Configuring default URL generation parameters

salt/journal/config/etc-nginx-sites-enabled-journal.conf, salt/journal/config/etc-nginx-traits.d-robots.conf, salt/journal/init.sls
~Tried initially to include a different robots configuration depending on the hostname, but `include` is apparently executed at startup time so it can't use variables. Will try to improve it once this basic form is online.~
Scenarios:
- `journal--end2end` and similar: only `norobots.conf` is used from `builder-base-formula`
- `journal--prod` with `elifesciences.org` host: `robots.conf` is used and prints `Disallow: ` which means allow anything
- `journal--prod` with other hosts: `robots.conf` is used, but it prints `Disallow: /`
=> Robots.txt only in production

salt/journal/config/etc-nginx-sites-enabled-journal.conf, salt/pillar/journal.sls
Such as elife.elifescience.org and similar ones. Uses `default_host` if specified, otherwise the standard autogenerated host name
=> Redirect old hostnames

salt/journal/init.sls, salt/journal/scripts/retrying-gulp-without-redis.sh
They both use lots of memory: the first one to run many parallel processes, the econd one as storage.
We have to check is Redis is present because on `dev` and `ci` it won't.
=> Gulp runs without Redis

salt/journal/config/etc-nginx-sites-enabled-journal.conf, salt/journal/config/srv-journal-app-config-parameters.yml, salt/journal/config/srv-journal-behat.yml, salt/pillar/journal.sls
At least in all places where it's strictly needed. This serves the purpose of making journal work on thedailybugle.org
`pillar.elife.domain` has been introduced in builder-base-formula and builder-private
Also, a bunch of things are not needed outside elife so we don't put them inside the nginx configuration.
=> Parameterizing elifesciences.org

salt/example.top, salt/journal/api-dummy.sls, salt/journal/config/etc-nginx-sites-enabled-api-dummy.conf, salt/journal/config/etc-nginx-sites-enabled-journal-local-demo.conf, salt/journal/init.sls, salt/pillar/journal.sls
Current status is api-dummy is deployed, but not actually used as journal-local-demo points to the `prod` API.
=> api-dummy working copy and virtual host

salt/journal/init.sls
According to the formulas, the Redis server should always be turned off locally when we are using Elasticache
=> Do not turn on/off Redis if it's not used

salt/journal/critical-css.sls
For https://github.com/elifesciences/journal/pull/789.
Full list in https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md, but this was enough for it to work.
=> Add packages required by Chrome headless

salt/journal/critical-css.sls
#34 still fails on end2end (can't reproduce by mimicking end2end in vagrant).
=> ELPP-3223 Full package list needed for Chrome headless

salt/journal/local-demo.sls
https://github.com/elifesciences/journal/pull/806 fails because the local demo's cache clearer seems to conflict when changing Symfony version. This changes it to run the post-install commands, which includes a cache clear (so should avoid bootstrapping the app, but also avoids using `rm -rf`).
=> Avoid bootstrapping Symfony when cleaning the local demo's cache

salt/journal/config/srv-journal-app-config-parameters.yml
`end2end` (and later `prod`) won't see the new ElastiCache configuration until this pull request is in. Can't really be fully tested in the formula build, as it doesn't have a variant with ElastiCache.
=> Support old/new ElastiCache CloudFormation outputs

salt/journal/critical-css.sls, salt/journal/init.sls, salt/journal/local-demo.sls
It still seems like a PR upgrading Symfony can create problems for builds that upgrade (eg https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fjournal/detail/PR-806/5/pipeline) or downgrades (ie separate PR, eg https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fjournal/detail/PR-809/1/pipeline)
=> Force Symfony cache cleans

salt/journal/config/srv-journal-app-config-parameters.yml
#43 broke in end2end as a long object wrapped, causing incorrect indentation.
This uses the `indent` filter to add the correct indent of any following lines, but also puts the value on a new line to avoid any inconsistencies, and to avoid having to calculate the indent (seems to work fine with any type). This also makes any diffs cleaner.
=> Fix YAML indentation

salt/journal/critical-css.sls
Seems that fresh instances get older versions that don't work (where as long-running instances have been updated), hence problems in #45.
Might also fix #36.
=> Update packages for Chromium

salt/journal/init.sls
Required by https://github.com/elifesciences/journal/pull/944 (we already clear the cache in the formula).
=> ELPP-3323 Cater for SensioDistributionBundle removal

salt/journal/config/etc-nginx-sites-available-journal.conf
These hostnames resolve to a CDN backed by redirects--prod. They should never get to this nginx.
=> Remove ported hostnames

salt/journal/config/etc-nginx-sites-available-journal.conf
`robots.txt` is the only dependency here, simple rename from the previous custom header.
=> ELPP-3393 Allow use of X-Forwarded-Host for robots.txt

salt/journal/local-demo.sls
Multiple `--include` and `--exclude` patterns lead to conflicts, so separating into a `cp` to fix the creation of `elife-loader.js`
=> Separate build/ copies from rsync

salt/journal/config/etc-nginx-sites-available-journal.conf
Follow up to #70, which gets the host right but sees the scheme as just `http`.
Thinking it should be possible to use the `X-Forwarded-*` headers here though.
=> ELPP-3732 Fix redirect scheme

salt/journal/config/etc-nginx-sites-available-journal.conf
Currently Fastly sends duplicates `X-Forwarded-Host` values.
Nginx's `hostnames` appears to only work with third-level domains when there are multiple values.
So:
- `X-Forwarded-Host: foo.elifesciences.org, foo.elifesciences.org` works
- `X-Forwarded-Host: elifesciences.org, elifesciences.org` doesn't
This uses regex to capture the first value and check that. (This should be reverted when only one value is sent.)
=> Handle multiple X-Forwarded-Host values

salt/journal/config/etc-nginx-traits.d-robots.conf
According to the logs, Googlebot (at least) is following the links to download files (which are streamed through Journal to add the `Content-Disposition` header). Don't think it's of any use to them, so we should stop bots from going to `/download/` paths.
=> Don't index download links

salt/journal/config/srv-journal-docker-compose.yml
`image` shouldn't be needed as it's in the Dockerfile.
=> Remove elifesciences/journal_web reference

salt/journal/config/etc-nginx-sites-available-journal.conf
Based on the 404 list in Google Search Console, eg
- `/elife/citation/371640/bibtex`
- `/keywords/polymeric-ig-receptor-pigr`
- `/cgi/reprint/3/0/e03604`
(And simplifies what's already there.)
=> Add redirects for old URLs

salt/journal/config/etc-nginx-traits.d-robots.conf
fyi @thewilkybarkid , @giorgiosironi 
not sure how this got past testing. I'd seen the highstate failures for a couple of days but the log files were empty. Today I ran highstate manually to see if that would trigger it and saw this. journal--prod--1 is down but journal--prod--2 is still up, presumably because highstate isn't run on subsequent nodes if it fails on the first
=> Fix: adds missing semi-colon to end of robots.txt line

salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf
This implements a redirect from the inside elife article to the press pack for the executive director appointment. As press pack is not supported for announcements this is the recognised work around for this issue.
=> Add redirect for executive director appointment

salt/journal/config/etc-syslog-ng-conf.d-journal.conf
Since the `journal.error.log` file contains all messages that are equal or more severe than `notice` I believe we can afford to not transfer the `journal.access.log` to loggly.
https://github.com/elifesciences/journal-formula/blob/40ae9465cf1f57ec19d8f322262f1e8c1c62f8ec/salt/journal/config/etc-nginx-sites-available-journal.conf#L193
=> Remove nginx access log from loggly transfer

salt/journal/config/etc-nginx-sites-available-journal.conf, salt/pillar/journal.sls
the journal should handle the landing page and it's trailing slash alias, everything else goes to EPP.
=> tweak to EPP redirect rules.

salt/journal/config/etc-nginx-sites-available-journal.conf, salt/pillar/journal.sls
Relates to https://github.com/elifesciences/enhanced-preprints-issues/issues/416
Depends on  https://github.com/elifesciences/builder-configuration/pull/304
If specified, implement an about page proxy that:
1) accepts anything but /about/people (which should be handle by journal)
2) transparently rewrites /about and /about/ to /about for the receiving proxy
2) transparently rewrites /about/* to /* for the receiving proxy
=> Proxy about pages

salt/journal/config/etc-nginx-sites-available-journal.conf
This is to resolve the base URL issue with pubpub before launch.
relates to: https://github.com/elifesciences/enhanced-preprints-issues/issues/416
=> add `/dist` as a proxy through to pubpub too. 

salt/journal/config/etc-nginx-sites-available-journal.conf, salt/pillar/journal.sls
This redirects the request before it reaches the journal app, avoiding the overhead of all the (soon to be obsolete) config there.
The key is awkward, because we're using a couple of similar sounding keys for journal config (that is only used in some environments anyway). We will be dropping that code soon, then we can rename keys in here and builder-configuration (if necessary) then.
Related PR: https://github.com/elifesciences/builder-configuration/pull/306
relates to: https://github.com/elifesciences/enhanced-preprints-issues/issues/414
=> add a new key to facilitate /submit redirect

salt/journal/config/etc-nginx-sites-available-journal.conf
Redirect is currently happening to the prod--journal hostname:
```
curl -sI https://elifesciences.org/about | grep location
location: http://prod--journal.elifesciences.org/about/
```
This PR fixes it to use public URL instead.
=> fix issue with redirecting to the host rather than the public url

salt/journal/config/etc-nginx-sites-available-journal.conf, salt/pillar/journal.sls
The continuumtest proxy is set on builder-configurations https://github.com/elifesciences/builder-configuration/commit/ad83e8d22b655e068707159cb54c7ae65494e321
=> add redirect privacy-policy and cookie-declaration to pubpub 

salt/journal/config/etc-nginx-traits.d-redirect-existing-paths.conf
Require for the browse by terms work
https://github.com/elifesciences/issues/issues/9146
=> Remove no longer required redirect to free up the endpoint
